var frankenwords = [
  'frankenword',
  'selfie',
  'couplie',
  'affluenza',
  'automagical',
  'avgas',
  'backronym',
  'banoffee',
  'bedaffle',
  'beefalo',
  'beerage',
  'beutifantistarific',
  'blurst',
  'bufugly',
  'chunnel',
  'chinglish',
  'cocacolonization',
  'conlang',
  'coopetition',
  'crisitunity',
  'crunk',
  'craptacular',
  'dancercise',
  'deliquid',
  'discustion',
  'disturbia',
  'dramastic',
  'dramedy',
  'ecoteur',
  'edutainment',
  'fantaulous',
  'fanzine',
  'flexicurity',
  'flong',
  'frankenfood',
  'frowcalculation',
  'fugly',
  'grasscycle',
  'herstory',
  'humanure',
  'insinnuendo',
  'intertwingle',
  'intertwangle',
  'mockney',
  'nastranaut',
  'netocracy',
  'oxbridge',
  'parkade',
  'pluot',
  'pomosexual',
  'prosumer',
  'screenager',
  'slanguage',
  'strunk',
  'tanorexia',
  'taardvark',
  'tofurkey'
];

var frankenRegex = new RegExp('\\b(' + frankenwords.join('|') + ')\\b', 'gi');
var matcher = require("./matcher");

module.exports = function (text) {
  return matcher(frankenRegex, text, "frankenword");
};
